// End point is the first access point for the app to interect with Spotify
export const authEndpoint = "https://accounts.spotify.com/authorize";

// Client Id generated by Spotify, when we registered the app in Spotify Developers portal 
const clientId = "cff76213089a4e228206c8bf120d67cb";
const redirectUri = "http://localhost:3000/";

// These are the behaviours the app performed allowed by the Spotify
const scopes = [
  "user-read-currently-playing",
  "user-read-recently-played",
  "streaming",
  "user-read-playback-state",
  "user-top-read",
  "user-modify-playback-state",
];

// Access URI bring the user to the Spotify user's authorization page
// Spotify attached back a token to the URI 
export const accessUrl = `${authEndpoint}?client_id=$
   {clientId}&redirect_uri=${redirectUri}&scope=$
   {scopes.join("%20")}&response_type=token&show_dialog=true`;

// This method used to retrive the token from the URI
// Token is essential, without it we can not access the API data
export const getTokenFromResponse = () => {
  return window.location.hash
    .substring(1)
    .split("&")
    .reduce((initial, item) => {
      var parts = item.split("=");
      initial[parts[0]] = decodeURIComponent(parts[1]);

      return initial;
    }, {});
};


